name: Docker Action With Post
description: Example Docker action that runs a post step.
author: QuasiDB
inputs:
  message:
    description: Message to print during the main step.
    required: false
    default: Running main step
  key:
    description: Key to use for caching.
    required: false
    default: "DefaultKey"
runs:
  using: docker
  image: Dockerfile
  entrypoint: /entrypoint.py
  post-entrypoint: /post.py
