FROM python:3.12-slim

COPY src /src
COPY entrypoint.py /entrypoint.py
COPY post.py /post.py
COPY requirements.txt /requirements.txt

RUN pip install --upgrade pip && pip install -r requirements.txt
RUN chmod +x /entrypoint.py /post.py