name: Test

on:
  workflow_dispatch:

jobs:
  generate-db:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Run Docker
        uses: ./.github/workflows/docker-action
        with:
          message: Running main step
